package com.wp.casino.messagenetty.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_server.proto

public final class PBCSMessage {
  private PBCSMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface proto_ww_user_data_change_reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_ww_user_data_change_req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 ply_guid = 1;</code>
     */
    long getPlyGuid();

    /**
     * <code>int32 type = 2;</code>
     */
    int getType();
  }
  /**
   * <pre>
   *发送用户道具变化通知
   * </pre>
   *
   * Protobuf type {@code proto_ww_user_data_change_req}
   */
  public  static final class proto_ww_user_data_change_req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_ww_user_data_change_req)
      proto_ww_user_data_change_reqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proto_ww_user_data_change_req.newBuilder() to construct.
    private proto_ww_user_data_change_req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proto_ww_user_data_change_req() {
      plyGuid_ = 0L;
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proto_ww_user_data_change_req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              plyGuid_ = input.readInt64();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBCSMessage.internal_static_proto_ww_user_data_change_req_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBCSMessage.internal_static_proto_ww_user_data_change_req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBCSMessage.proto_ww_user_data_change_req.class, PBCSMessage.proto_ww_user_data_change_req.Builder.class);
    }

    public static final int PLY_GUID_FIELD_NUMBER = 1;
    private long plyGuid_;
    /**
     * <code>int64 ply_guid = 1;</code>
     */
    public long getPlyGuid() {
      return plyGuid_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (plyGuid_ != 0L) {
        output.writeInt64(1, plyGuid_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (plyGuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, plyGuid_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBCSMessage.proto_ww_user_data_change_req)) {
        return super.equals(obj);
      }
      PBCSMessage.proto_ww_user_data_change_req other = (PBCSMessage.proto_ww_user_data_change_req) obj;

      boolean result = true;
      result = result && (getPlyGuid()
          == other.getPlyGuid());
      result = result && (getType()
          == other.getType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLY_GUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlyGuid());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBCSMessage.proto_ww_user_data_change_req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *发送用户道具变化通知
     * </pre>
     *
     * Protobuf type {@code proto_ww_user_data_change_req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_ww_user_data_change_req)
        PBCSMessage.proto_ww_user_data_change_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_req_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBCSMessage.proto_ww_user_data_change_req.class, PBCSMessage.proto_ww_user_data_change_req.Builder.class);
      }

      // Construct using PBCSMessage.proto_ww_user_data_change_req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        plyGuid_ = 0L;

        type_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_req_descriptor;
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_req getDefaultInstanceForType() {
        return PBCSMessage.proto_ww_user_data_change_req.getDefaultInstance();
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_req build() {
        PBCSMessage.proto_ww_user_data_change_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_req buildPartial() {
        PBCSMessage.proto_ww_user_data_change_req result = new PBCSMessage.proto_ww_user_data_change_req(this);
        result.plyGuid_ = plyGuid_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBCSMessage.proto_ww_user_data_change_req) {
          return mergeFrom((PBCSMessage.proto_ww_user_data_change_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBCSMessage.proto_ww_user_data_change_req other) {
        if (other == PBCSMessage.proto_ww_user_data_change_req.getDefaultInstance()) return this;
        if (other.getPlyGuid() != 0L) {
          setPlyGuid(other.getPlyGuid());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBCSMessage.proto_ww_user_data_change_req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBCSMessage.proto_ww_user_data_change_req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long plyGuid_ ;
      /**
       * <code>int64 ply_guid = 1;</code>
       */
      public long getPlyGuid() {
        return plyGuid_;
      }
      /**
       * <code>int64 ply_guid = 1;</code>
       */
      public Builder setPlyGuid(long value) {

        plyGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ply_guid = 1;</code>
       */
      public Builder clearPlyGuid() {

        plyGuid_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_ww_user_data_change_req)
    }

    // @@protoc_insertion_point(class_scope:proto_ww_user_data_change_req)
    private static final PBCSMessage.proto_ww_user_data_change_req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBCSMessage.proto_ww_user_data_change_req();
    }

    public static PBCSMessage.proto_ww_user_data_change_req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proto_ww_user_data_change_req>
        PARSER = new com.google.protobuf.AbstractParser<proto_ww_user_data_change_req>() {
      @Override
      public proto_ww_user_data_change_req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proto_ww_user_data_change_req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proto_ww_user_data_change_req> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<proto_ww_user_data_change_req> getParserForType() {
      return PARSER;
    }

    @Override
    public PBCSMessage.proto_ww_user_data_change_req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface proto_ww_user_data_change_notiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_ww_user_data_change_noti)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *接收用户道具变化结果通知
   * </pre>
   *
   * Protobuf type {@code proto_ww_user_data_change_noti}
   */
  public  static final class proto_ww_user_data_change_noti extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_ww_user_data_change_noti)
      proto_ww_user_data_change_notiOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proto_ww_user_data_change_noti.newBuilder() to construct.
    private proto_ww_user_data_change_noti(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proto_ww_user_data_change_noti() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proto_ww_user_data_change_noti(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBCSMessage.internal_static_proto_ww_user_data_change_noti_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBCSMessage.internal_static_proto_ww_user_data_change_noti_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBCSMessage.proto_ww_user_data_change_noti.class, PBCSMessage.proto_ww_user_data_change_noti.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBCSMessage.proto_ww_user_data_change_noti)) {
        return super.equals(obj);
      }
      PBCSMessage.proto_ww_user_data_change_noti other = (PBCSMessage.proto_ww_user_data_change_noti) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_user_data_change_noti parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBCSMessage.proto_ww_user_data_change_noti prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *接收用户道具变化结果通知
     * </pre>
     *
     * Protobuf type {@code proto_ww_user_data_change_noti}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_ww_user_data_change_noti)
        PBCSMessage.proto_ww_user_data_change_notiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_noti_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_noti_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBCSMessage.proto_ww_user_data_change_noti.class, PBCSMessage.proto_ww_user_data_change_noti.Builder.class);
      }

      // Construct using PBCSMessage.proto_ww_user_data_change_noti.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBCSMessage.internal_static_proto_ww_user_data_change_noti_descriptor;
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_noti getDefaultInstanceForType() {
        return PBCSMessage.proto_ww_user_data_change_noti.getDefaultInstance();
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_noti build() {
        PBCSMessage.proto_ww_user_data_change_noti result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBCSMessage.proto_ww_user_data_change_noti buildPartial() {
        PBCSMessage.proto_ww_user_data_change_noti result = new PBCSMessage.proto_ww_user_data_change_noti(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBCSMessage.proto_ww_user_data_change_noti) {
          return mergeFrom((PBCSMessage.proto_ww_user_data_change_noti)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBCSMessage.proto_ww_user_data_change_noti other) {
        if (other == PBCSMessage.proto_ww_user_data_change_noti.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBCSMessage.proto_ww_user_data_change_noti parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBCSMessage.proto_ww_user_data_change_noti) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_ww_user_data_change_noti)
    }

    // @@protoc_insertion_point(class_scope:proto_ww_user_data_change_noti)
    private static final PBCSMessage.proto_ww_user_data_change_noti DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBCSMessage.proto_ww_user_data_change_noti();
    }

    public static PBCSMessage.proto_ww_user_data_change_noti getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proto_ww_user_data_change_noti>
        PARSER = new com.google.protobuf.AbstractParser<proto_ww_user_data_change_noti>() {
      @Override
      public proto_ww_user_data_change_noti parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proto_ww_user_data_change_noti(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proto_ww_user_data_change_noti> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<proto_ww_user_data_change_noti> getParserForType() {
      return PARSER;
    }

    @Override
    public PBCSMessage.proto_ww_user_data_change_noti getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface proto_ww_friend_msg_reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_ww_friend_msg_req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string rcv_guid = 1;</code>
     */
    String getRcvGuid();
    /**
     * <code>string rcv_guid = 1;</code>
     */
    com.google.protobuf.ByteString
        getRcvGuidBytes();

    /**
     * <code>string message = 2;</code>
     */
    String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string type = 3;</code>
     */
    String getType();
    /**
     * <code>string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * <pre>
   *发送好友消息通知
   * </pre>
   *
   * Protobuf type {@code proto_ww_friend_msg_req}
   */
  public  static final class proto_ww_friend_msg_req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_ww_friend_msg_req)
      proto_ww_friend_msg_reqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proto_ww_friend_msg_req.newBuilder() to construct.
    private proto_ww_friend_msg_req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proto_ww_friend_msg_req() {
      rcvGuid_ = "";
      message_ = "";
      type_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proto_ww_friend_msg_req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              rcvGuid_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBCSMessage.internal_static_proto_ww_friend_msg_req_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBCSMessage.internal_static_proto_ww_friend_msg_req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBCSMessage.proto_ww_friend_msg_req.class, PBCSMessage.proto_ww_friend_msg_req.Builder.class);
    }

    public static final int RCV_GUID_FIELD_NUMBER = 1;
    private volatile Object rcvGuid_;
    /**
     * <code>string rcv_guid = 1;</code>
     */
    public String getRcvGuid() {
      Object ref = rcvGuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rcvGuid_ = s;
        return s;
      }
    }
    /**
     * <code>string rcv_guid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRcvGuidBytes() {
      Object ref = rcvGuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rcvGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile Object type_;
    /**
     * <code>string type = 3;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRcvGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rcvGuid_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRcvGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rcvGuid_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBCSMessage.proto_ww_friend_msg_req)) {
        return super.equals(obj);
      }
      PBCSMessage.proto_ww_friend_msg_req other = (PBCSMessage.proto_ww_friend_msg_req) obj;

      boolean result = true;
      result = result && getRcvGuid()
          .equals(other.getRcvGuid());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getType()
          .equals(other.getType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RCV_GUID_FIELD_NUMBER;
      hash = (53 * hash) + getRcvGuid().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBCSMessage.proto_ww_friend_msg_req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *发送好友消息通知
     * </pre>
     *
     * Protobuf type {@code proto_ww_friend_msg_req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_ww_friend_msg_req)
        PBCSMessage.proto_ww_friend_msg_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_req_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBCSMessage.proto_ww_friend_msg_req.class, PBCSMessage.proto_ww_friend_msg_req.Builder.class);
      }

      // Construct using PBCSMessage.proto_ww_friend_msg_req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rcvGuid_ = "";

        message_ = "";

        type_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_req_descriptor;
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_req getDefaultInstanceForType() {
        return PBCSMessage.proto_ww_friend_msg_req.getDefaultInstance();
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_req build() {
        PBCSMessage.proto_ww_friend_msg_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_req buildPartial() {
        PBCSMessage.proto_ww_friend_msg_req result = new PBCSMessage.proto_ww_friend_msg_req(this);
        result.rcvGuid_ = rcvGuid_;
        result.message_ = message_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBCSMessage.proto_ww_friend_msg_req) {
          return mergeFrom((PBCSMessage.proto_ww_friend_msg_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBCSMessage.proto_ww_friend_msg_req other) {
        if (other == PBCSMessage.proto_ww_friend_msg_req.getDefaultInstance()) return this;
        if (!other.getRcvGuid().isEmpty()) {
          rcvGuid_ = other.rcvGuid_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBCSMessage.proto_ww_friend_msg_req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBCSMessage.proto_ww_friend_msg_req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object rcvGuid_ = "";
      /**
       * <code>string rcv_guid = 1;</code>
       */
      public String getRcvGuid() {
        Object ref = rcvGuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rcvGuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string rcv_guid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRcvGuidBytes() {
        Object ref = rcvGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rcvGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rcv_guid = 1;</code>
       */
      public Builder setRcvGuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        rcvGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rcv_guid = 1;</code>
       */
      public Builder clearRcvGuid() {

        rcvGuid_ = getDefaultInstance().getRcvGuid();
        onChanged();
        return this;
      }
      /**
       * <code>string rcv_guid = 1;</code>
       */
      public Builder setRcvGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        rcvGuid_ = value;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {

        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        message_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 3;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_ww_friend_msg_req)
    }

    // @@protoc_insertion_point(class_scope:proto_ww_friend_msg_req)
    private static final PBCSMessage.proto_ww_friend_msg_req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBCSMessage.proto_ww_friend_msg_req();
    }

    public static PBCSMessage.proto_ww_friend_msg_req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proto_ww_friend_msg_req>
        PARSER = new com.google.protobuf.AbstractParser<proto_ww_friend_msg_req>() {
      @Override
      public proto_ww_friend_msg_req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proto_ww_friend_msg_req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proto_ww_friend_msg_req> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<proto_ww_friend_msg_req> getParserForType() {
      return PARSER;
    }

    @Override
    public PBCSMessage.proto_ww_friend_msg_req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface proto_ww_friend_msg_notiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_ww_friend_msg_noti)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *接收好友消息通知
   * </pre>
   *
   * Protobuf type {@code proto_ww_friend_msg_noti}
   */
  public  static final class proto_ww_friend_msg_noti extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_ww_friend_msg_noti)
      proto_ww_friend_msg_notiOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proto_ww_friend_msg_noti.newBuilder() to construct.
    private proto_ww_friend_msg_noti(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proto_ww_friend_msg_noti() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proto_ww_friend_msg_noti(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBCSMessage.internal_static_proto_ww_friend_msg_noti_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBCSMessage.internal_static_proto_ww_friend_msg_noti_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBCSMessage.proto_ww_friend_msg_noti.class, PBCSMessage.proto_ww_friend_msg_noti.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBCSMessage.proto_ww_friend_msg_noti)) {
        return super.equals(obj);
      }
      PBCSMessage.proto_ww_friend_msg_noti other = (PBCSMessage.proto_ww_friend_msg_noti) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCSMessage.proto_ww_friend_msg_noti parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBCSMessage.proto_ww_friend_msg_noti prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *接收好友消息通知
     * </pre>
     *
     * Protobuf type {@code proto_ww_friend_msg_noti}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_ww_friend_msg_noti)
        PBCSMessage.proto_ww_friend_msg_notiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_noti_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_noti_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBCSMessage.proto_ww_friend_msg_noti.class, PBCSMessage.proto_ww_friend_msg_noti.Builder.class);
      }

      // Construct using PBCSMessage.proto_ww_friend_msg_noti.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBCSMessage.internal_static_proto_ww_friend_msg_noti_descriptor;
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_noti getDefaultInstanceForType() {
        return PBCSMessage.proto_ww_friend_msg_noti.getDefaultInstance();
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_noti build() {
        PBCSMessage.proto_ww_friend_msg_noti result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBCSMessage.proto_ww_friend_msg_noti buildPartial() {
        PBCSMessage.proto_ww_friend_msg_noti result = new PBCSMessage.proto_ww_friend_msg_noti(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBCSMessage.proto_ww_friend_msg_noti) {
          return mergeFrom((PBCSMessage.proto_ww_friend_msg_noti)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBCSMessage.proto_ww_friend_msg_noti other) {
        if (other == PBCSMessage.proto_ww_friend_msg_noti.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBCSMessage.proto_ww_friend_msg_noti parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBCSMessage.proto_ww_friend_msg_noti) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_ww_friend_msg_noti)
    }

    // @@protoc_insertion_point(class_scope:proto_ww_friend_msg_noti)
    private static final PBCSMessage.proto_ww_friend_msg_noti DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBCSMessage.proto_ww_friend_msg_noti();
    }

    public static PBCSMessage.proto_ww_friend_msg_noti getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proto_ww_friend_msg_noti>
        PARSER = new com.google.protobuf.AbstractParser<proto_ww_friend_msg_noti>() {
      @Override
      public proto_ww_friend_msg_noti parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proto_ww_friend_msg_noti(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proto_ww_friend_msg_noti> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<proto_ww_friend_msg_noti> getParserForType() {
      return PARSER;
    }

    @Override
    public PBCSMessage.proto_ww_friend_msg_noti getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ww_user_data_change_req_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ww_user_data_change_req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ww_user_data_change_noti_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ww_user_data_change_noti_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ww_friend_msg_req_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ww_friend_msg_req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ww_friend_msg_noti_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ww_friend_msg_noti_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023client_server.proto\"?\n\035proto_ww_user_d" +
      "ata_change_req\022\020\n\010ply_guid\030\001 \001(\003\022\014\n\004type" +
      "\030\002 \001(\005\" \n\036proto_ww_user_data_change_noti" +
      "\"J\n\027proto_ww_friend_msg_req\022\020\n\010rcv_guid\030" +
      "\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\"\032\n\030" +
      "proto_ww_friend_msg_notiB\017B\013PBCSMessageH" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ww_user_data_change_req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ww_user_data_change_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ww_user_data_change_req_descriptor,
        new String[] { "PlyGuid", "Type", });
    internal_static_proto_ww_user_data_change_noti_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ww_user_data_change_noti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ww_user_data_change_noti_descriptor,
        new String[] { });
    internal_static_proto_ww_friend_msg_req_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ww_friend_msg_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ww_friend_msg_req_descriptor,
        new String[] { "RcvGuid", "Message", "Type", });
    internal_static_proto_ww_friend_msg_noti_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ww_friend_msg_noti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ww_friend_msg_noti_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
