server:
    port: 8188
    bind_address: 0.0.0.0
    bind_port: 9876
mongodb:
    message:
        database: message
        host: 3.6.110.15 #s3.hiigame.net
        port: 27017
    replay:
        database: db_replay
        host: 3.6.110.15 #s3.hiigame.net
        port: 27017
    record:
        database: db_record
        host: 3.6.110.15 #s3.hiigame.net
        port: 27017
spring:
    datasource:
        url: jdbc:mysql://192.168.0.123:3306/db_casino?useUnicode=true&characterEncoding=utf-8
        username: wolfplus
        password: passthis
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
        open-in-view: false