server:
    port: 8188
    #作为服务端监听的端口
    bind_address: 0.0.0.0
    bind_port: 9876
    #作为客户端连接的服务端的地址和端口
    client_address: 127.0.0.1
    client_port: 9123
    client_heartbeat: 1 #1为断线重连，其他值不重连
    client_interval: 10 #断线重连的心跳间隔，单位s
mongodb:
    message:
        database: message
        host: 192.168.0.123
        port: 27017
    replay:
        database: db_replay
        host: 192.168.0.123
        port: 27017
    record:
        database: db_record
        host: 192.168.0.123
        port: 27017
spring:
    datasource:
        url: jdbc:mysql://192.168.0.123:3306/db_casino?useUnicode=true&characterEncoding=utf-8
        username: wolfplus
        password: passthis
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
        open-in-view: false