## springboot整合rabbitmq的基本配置
#spring:
#  datasource:
#      url: jdbc:mysql://106.12.69.57:3306/biaozhen?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: Sn442348
#      driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
#    open-in-view: false
server:
    port: 8188

